---
date: 2021-05-16T06:34
tags: 
  - rust
---

# Rust: Error handling

- recoverable and unrecoverable errors
- unrecoverable errors: direct call to `panic!()`, or array index out of bounds (which leads to call to panic macro).  
There are two options here wrt stack - unwind the stack (default, but lots of work) or abort directly (and allow OS to reclaim the space). This can be configured in toml file.

- recoverable errors: `Result<T, E>`
- ways to handle recoverable error: match construct, closure construct, `?` operator - this operator works on any trait extending (??) `Try` like `Result` for example
- propagating errors

```rust

fn openfile4() -> Result<String, io::Error> {
    let mut s = String::new();
    File::open("hello3.txt")?.read_to_string(&mut s)?;
    Ok(s)
}
```

using match operators:

```rust

    let result = File::open("hello.txt");
    let f: Result<File, std::io::Error> = match result {
        Ok(f) => Ok(f),
        Err(e) => match e.kind() {
            std::io::ErrorKind::NotFound => File::create("hello.txt"),
            e => Err(std::io::Error::new(e, "error")),
        },
    };

    match f {
        Ok(mut fileh) => {
            let mut s = String::new();
            match fileh.read_to_string(&mut s) {
                Ok(_) => Ok(s),
                Err(ef) => Err(ef),
            }
        },
        eff => eff
    }
```

using closures

```rust
let f = File::open("hello.txt").unwrap_or_else(|error| {
        if error.kind() == ErrorKind::NotFound {
            File::create("hello.txt").unwrap_or_else(|error| {
                panic!("Problem creating the file: {:?}", error);
            })
        } else {
            panic!("Problem opening the file: {:?}", error);
        }
    });
```
